export class StorageServiceKeyConstants {
    public static USER_DATA_SETTINGS = 'USER_DATA_SETTINGS';
    public static USER_DATA_SAVED_AREAS = "ESKOM_SE_PUSH_SAVED_AREAS";
    public static USER_DATA_ALLOWANCE = "USER_DATA_ALLOWANCE";

    public static API_RESPONSE_GETSTATUS = 'API_RESPONSE_GETSTATUS';
    public static API_RESPONSE_GETAREAINFO = 'API_RESPONSE_GETAREAINFO';
    public static API_RESPONSE_GETAREASNEARBY = 'API_RESPONSE_GETAREASNEARBY';
    public static API_RESPONSE_GETAREA = 'API_RESPONSE_GETAREA';
    public static API_RESPONSE_GETTOPICNEARBY = 'API_RESPONSE_GETTOPICNEARBY';
}